# Generated by Django 3.1.2 on 2021-01-12 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(choices=[('Electricity', 'Electricity'), ('Meal', 'Meal'), ('Rent', 'Rent'), ('Security', 'Security'), ('Others', 'Others')], max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.CreateModel(
            name='Percentages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percent', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Percentages',
            },
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('buying_price_per_each', models.FloatField(default=0)),
                ('selling_price_per_each', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('ordered', models.BooleanField(default=False, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('postal_address', models.CharField(blank=True, max_length=200, null=True)),
                ('physical_address', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_TIN', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_VRN', models.CharField(blank=True, max_length=200, null=True)),
                ('profoma', models.BooleanField(default=False, null=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('quantity_before', models.PositiveIntegerField(default=0)),
                ('quantity_after', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='istock_app.products')),
            ],
            options={
                'verbose_name_plural': 'Purchases',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('buying_price', models.FloatField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='istock_app.products')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='istock_app.sales')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_date', models.DateField()),
                ('last_date', models.DateField()),
                ('deposition_date', models.DateField()),
                ('amount', models.FloatField()),
                ('bank', models.CharField(max_length=50)),
                ('deposited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Deposits',
            },
        ),
    ]
