# Generated by Django 3.1.2 on 2021-02-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('istock_app', '0002_auto_20210124_1721'),
        ('istock_app', '0002_auto_20210124_1741'),
    ]

    operations = [
    ]
