# Generated by Django 3.1.2 on 2021-02-05 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istock_app', '0003_merge_20210202_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 22, 49, 36, 599543), null=True),
        ),
    ]
