# Generated by Django 3.1.5 on 2021-02-07 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('istock_app', '0003_merge_20210202_1841'),
        ('istock_app', '0004_auto_20210205_2249'),
    ]

    operations = [
    ]
