# Generated by Django 3.1.2 on 2021-05-29 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istock_app', '0008_auto_20210211_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 29, 19, 19, 37, 428555), null=True),
        ),
    ]
